export const practicalProjects = [
  {
    id: "project-module-0",
    moduleId: "module-0",
    moduleTitle: "Introduction to Artificial Intelligence",
    title: "Build Your Personal AI Workday Assistant",
    summary: "Create a simple AI routine that helps you plan, learn, and complete one real task this week.",
    tools: ["ChatGPT Free", "Google Docs"],
    difficulty: "Starter",
    estimatedMinutes: 45,
    prompt: "Act as my practical AI workday assistant. Ask me for my role, one goal for this week, my available time, and my biggest blocker. Then create a realistic three-step plan, a checklist, and one reusable prompt I can use tomorrow.",
    deliverable: "A one-page AI workday plan with one completed task and the reusable prompt.",
    steps: ["Choose one real school, work, or business goal.", "Run the prompt and answer the assistant's questions honestly.", "Complete the first task and save the plan in Google Docs.", "Add a short note explaining what AI helped you do."]
  },
  {
    id: "project-module-1",
    moduleId: "module-1",
    moduleTitle: "ChatGPT & Advanced Prompting",
    title: "Create a Reusable Prompt Toolkit",
    summary: "Turn one repeated task into a tested prompt template with examples and correction instructions.",
    tools: ["ChatGPT Free", "Google Docs"],
    difficulty: "Starter",
    estimatedMinutes: 60,
    prompt: "Help me create a reusable prompt template for [choose a real task]. Include a clear role, goal, context fields, constraints, output format, one example, and a correction prompt. Test it with two different inputs and improve it after each test.",
    deliverable: "Three tested prompts saved as a mini prompt toolkit.",
    steps: ["Pick a repeated task such as captions, proposals, research, or study notes.", "Build the first template with placeholders.", "Test it with two real examples.", "Record the original output, correction prompt, and improved output."]
  },
  {
    id: "project-module-2",
    moduleId: "module-2",
    moduleTitle: "AI Tools for Graphic Design",
    title: "Design a Launch Flyer for a Real Offer",
    summary: "Create a clear promotional flyer for a real product, service, event, or class.",
    tools: ["Canva Free", "ChatGPT Free"],
    difficulty: "Starter",
    estimatedMinutes: 90,
    prompt: "Write concise flyer copy for [offer]. Give me a strong headline, one benefit-led subtitle, three short benefits, a clear call to action, and a trustworthy contact line. Keep the language simple and suitable for a mobile-first flyer.",
    deliverable: "One square social flyer and one short caption for the same offer.",
    steps: ["Choose a real offer and define its audience.", "Generate and edit the copy with ChatGPT.", "Build the design in Canva using one clear visual hierarchy.", "Export the flyer and ask one person whether the offer is understandable in five seconds."]
  },
  {
    id: "project-module-3",
    moduleId: "module-3",
    moduleTitle: "Photo Editing & Image Enhancement",
    title: "Create a Before-and-After Product Image",
    summary: "Improve a real product or profile image and document the editing decisions.",
    tools: ["Photopea Free", "Canva Free", "remove.bg Free"],
    difficulty: "Starter",
    estimatedMinutes: 75,
    prompt: "Review this product image description: [describe the image]. Give me a professional editing checklist for lighting, crop, background, contrast, color, and export size. Prioritize changes that improve trust and clarity without making the product look fake.",
    deliverable: "A before-and-after image pair with a five-point editing note.",
    steps: ["Choose a clear image you own or have permission to edit.", "Remove distractions and improve the crop/background.", "Adjust light and color while keeping the product realistic.", "Export web-ready JPG and compare it beside the original."]
  },
  {
    id: "project-module-4",
    moduleId: "module-4",
    moduleTitle: "AI Video & Movie Creation",
    title: "Produce a 30-Second Promo Video",
    summary: "Turn a real offer or personal story into a short vertical video with a clear hook and call to action.",
    tools: ["CapCut Free", "Canva Free", "ChatGPT Free"],
    difficulty: "Intermediate",
    estimatedMinutes: 120,
    prompt: "Create a 30-second vertical video script for [offer/topic]. Structure it as a three-second hook, problem, useful proof or demo, benefit, and call to action. Give me on-screen text and a shot list for each scene.",
    deliverable: "One 9:16 video under 30 seconds with captions and a call to action.",
    steps: ["Choose one audience and one outcome.", "Generate the script and shot list.", "Collect or record simple footage you own.", "Edit in CapCut, add captions, export, and ask whether the first three seconds create curiosity."]
  },
  {
    id: "project-module-5",
    moduleId: "module-5",
    moduleTitle: "Cartoon & Animation Creation",
    title: "Animate a Short Story for a Brand",
    summary: "Create a simple character or visual story that communicates one idea in under 20 seconds.",
    tools: ["Canva Free", "CapCut Free", "ChatGPT Free"],
    difficulty: "Intermediate",
    estimatedMinutes: 100,
    prompt: "Write a four-scene micro-story for [brand or topic]. Each scene must have one visual action, one short line of narration, and one emotion. Keep it clear enough for a viewer who has no context.",
    deliverable: "A four-scene animated short with narration or captions.",
    steps: ["Pick a simple message and audience.", "Generate the four-scene storyboard.", "Create or select consistent visuals for each scene.", "Animate the scenes, add captions, and export the final short."]
  },
  {
    id: "project-module-6",
    moduleId: "module-6",
    moduleTitle: "Website Development with AI",
    title: "Build a One-Page Service Website",
    summary: "Create a useful one-page site for a real service with clear information and a working contact action.",
    tools: ["ChatGPT Free", "Google Sites or Canva Websites", "Google Forms"],
    difficulty: "Intermediate",
    estimatedMinutes: 120,
    prompt: "Plan a one-page website for [service]. Give me the page sections, a clear headline, benefits, proof section, FAQ, call to action, and a simple mobile-first content structure. Avoid vague marketing language.",
    deliverable: "A published one-page site or clickable prototype with a working contact form.",
    steps: ["Choose a real service and target audience.", "Generate the content structure and edit it for truthfulness.", "Build the page with a free site builder.", "Test it on a phone and submit the live link with one improvement you would make next."]
  },
  {
    id: "project-module-7",
    moduleId: "module-7",
    moduleTitle: "Excel & Spreadsheet Automation with AI",
    title: "Build a Small Business Tracker",
    summary: "Create a Google Sheet that turns raw entries into useful totals and decisions.",
    tools: ["Google Sheets", "ChatGPT Free"],
    difficulty: "Intermediate",
    estimatedMinutes: 100,
    prompt: "Help me design a Google Sheets tracker for [business or personal process]. Define the columns, validation rules, formulas, summary metrics, and one simple chart. Explain every formula in plain language.",
    deliverable: "A working tracker with sample data, formulas, a summary area, and one chart.",
    steps: ["Choose a process such as sales, expenses, attendance, or content.", "Ask for the table and formulas.", "Build and test the sheet with at least ten sample rows.", "Write three decisions the tracker can help someone make."]
  },
  {
    id: "project-module-8",
    moduleId: "module-8",
    moduleTitle: "Content & Advertisement Creation with AI",
    title: "Create a Mini Campaign for One Offer",
    summary: "Plan a small campaign with a message, advert variations, and a simple publishing schedule.",
    tools: ["ChatGPT Free", "Canva Free", "Google Sheets"],
    difficulty: "Intermediate",
    estimatedMinutes: 110,
    prompt: "Create a five-day campaign for [offer] aimed at [audience]. Provide one campaign idea, five post angles, two short ad variations, visual direction, calls to action, and a simple measurement plan.",
    deliverable: "A five-day campaign sheet with two ad creatives and success metrics.",
    steps: ["Define the offer and audience pain point.", "Generate the campaign and remove unsupported claims.", "Design two matching visuals in Canva.", "Publish or present the campaign plan and explain what metric matters most."]
  },
  {
    id: "project-module-9",
    moduleId: "module-9",
    moduleTitle: "Social Media Content Generation with AI",
    title: "Build a 7-Day Content Calendar",
    summary: "Create a practical weekly calendar with useful content, proof, conversation, and conversion posts.",
    tools: ["ChatGPT Free", "Canva Free", "Google Sheets"],
    difficulty: "Starter",
    estimatedMinutes: 90,
    prompt: "Build a seven-day content calendar for [brand]. Use a mix of education, story, proof, conversation, and offer posts. For each day include a hook, caption outline, visual idea, call to action, and one simple metric.",
    deliverable: "A seven-day calendar and three ready-to-publish posts.",
    steps: ["Choose a real brand or personal project.", "Generate the calendar and add real examples/proof.", "Design three visual posts.", "Schedule or present the calendar and explain the content mix."]
  },
  {
    id: "project-module-10",
    moduleId: "module-10",
    moduleTitle: "Business & Productivity Tools with AI",
    title: "Design a Personal Productivity System",
    summary: "Combine a weekly plan, task list, and reusable AI routine for one real responsibility.",
    tools: ["Notion Free or Google Docs", "Google Calendar", "ChatGPT Free"],
    difficulty: "Starter",
    estimatedMinutes: 75,
    prompt: "Design a simple weekly productivity system for my role as [role]. Include a capture list, weekly priorities, daily planning routine, review questions, and one AI prompt for turning notes into next actions.",
    deliverable: "A usable weekly workspace and a one-week reflection.",
    steps: ["List your recurring responsibilities.", "Choose three priority outcomes for the week.", "Build the workspace and schedule review times.", "Use it for five days and record what improved or failed."]
  },
  {
    id: "project-module-11",
    moduleId: "module-11",
    moduleTitle: "Data Analysis & Research with AI",
    title: "Turn a Small Dataset into a Decision Brief",
    summary: "Analyze a clean, non-sensitive dataset and communicate one evidence-based recommendation.",
    tools: ["Google Sheets", "ChatGPT Free", "Google Docs"],
    difficulty: "Intermediate",
    estimatedMinutes: 120,
    prompt: "Help me analyze this dataset without inventing facts. Identify the important columns, clean-up checks, useful summaries, possible patterns, limitations, and three questions I should investigate before making a decision.",
    deliverable: "A one-page decision brief with a chart, three findings, and limitations.",
    steps: ["Use public or invented data with no private information.", "Clean and summarize the data in Sheets.", "Ask ChatGPT for analysis questions, not made-up conclusions.", "Write one recommendation supported by the chart and note the limitations."]
  },
  {
    id: "project-module-12",
    moduleId: "module-12",
    moduleTitle: "AI for Students & Everyday Use",
    title: "Create a Personal Study Coach",
    summary: "Build a repeatable study workflow that turns one topic into notes, questions, and a revision plan.",
    tools: ["ChatGPT Free", "Google Docs"],
    difficulty: "Starter",
    estimatedMinutes: 60,
    prompt: "Act as a patient study coach for [topic]. First ask what I already know. Then explain the topic simply, give me five questions one at a time, correct my answers, and finish with a three-day revision plan.",
    deliverable: "A study guide, corrected question set, and three-day revision plan.",
    steps: ["Choose a real subject or skill.", "Use the prompt as an interactive conversation.", "Save the corrected answers and key explanations.", "Follow the revision plan and record one remaining question."]
  },
  {
    id: "project-module-13",
    moduleId: "module-13",
    moduleTitle: "Mobile App Creation with AI",
    title: "Prototype a Useful Community App",
    summary: "Design a simple app concept that solves one real information or coordination problem.",
    tools: ["Google Sheets", "Glide Free or AppSheet", "ChatGPT Free"],
    difficulty: "Advanced",
    estimatedMinutes: 150,
    prompt: "Help me design a small mobile app for [audience] to solve [problem]. Define the user, core workflow, data tables, screens, fields, empty states, and one privacy risk. Keep the first version small enough to prototype in a no-code builder.",
    deliverable: "A clickable prototype or working no-code app with sample data.",
    steps: ["Interview one potential user or write down the real need.", "Design the smallest useful workflow and data table.", "Build the prototype with a free no-code tool.", "Test one task with a user and document the feedback."]
  },
  {
    id: "project-module-14",
    moduleId: "module-14",
    moduleTitle: "Making Money with AI Tools",
    title: "Package and Pitch a Real AI Service",
    summary: "Turn one learned skill into a truthful service offer with proof, pricing logic, and a client message.",
    tools: ["ChatGPT Free", "Canva Free", "Google Docs"],
    difficulty: "Advanced",
    estimatedMinutes: 120,
    prompt: "Help me package a beginner-friendly AI service for [target client]. Create a clear offer, deliverables, boundaries, three package options, a proof plan, a fair pricing explanation, and a short outreach message. Do not promise results I cannot prove.",
    deliverable: "A one-page service offer, one sample portfolio piece, and one client outreach message.",
    steps: ["Choose a client type and one specific problem.", "Create the service scope and proof sample.", "Design the one-page offer in Canva or Docs.", "Send or role-play the outreach message and record the feedback."]
  }
];

export function findPracticalProject(projectId) {
  return practicalProjects.find((project) => project.id === projectId) || null;
}
